name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Create Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Permissions
        run: chmod +x build.sh
        shell: bash

      - name: Build
        run: ./build.sh
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: touchpoint-wp
          path: build
